// This file is generated by rust-protobuf 2.14.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `replication.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_14_0;

#[derive(PartialEq,Clone,Default)]
pub struct Replication {
    // message fields
    pub header: ::std::string::String,
    pub cids_bytes: ::protobuf::RepeatedField<::std::vec::Vec<u8>>,
    pub servers: ::protobuf::RepeatedField<ServerSource>,
    pub replication_factor: i32,
    pub refresh_interval_seconds: i32,
    pub server_down_delay_seconds: i32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Replication {
    fn default() -> &'a Replication {
        <Replication as ::protobuf::Message>::default_instance()
    }
}

impl Replication {
    pub fn new() -> Replication {
        ::std::default::Default::default()
    }

    // string header = 1;


    pub fn get_header(&self) -> &str {
        &self.header
    }
    pub fn clear_header(&mut self) {
        self.header.clear();
    }

    // Param is passed by value, moved
    pub fn set_header(&mut self, v: ::std::string::String) {
        self.header = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_header(&mut self) -> &mut ::std::string::String {
        &mut self.header
    }

    // Take field
    pub fn take_header(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.header, ::std::string::String::new())
    }

    // repeated bytes cids_bytes = 2;


    pub fn get_cids_bytes(&self) -> &[::std::vec::Vec<u8>] {
        &self.cids_bytes
    }
    pub fn clear_cids_bytes(&mut self) {
        self.cids_bytes.clear();
    }

    // Param is passed by value, moved
    pub fn set_cids_bytes(&mut self, v: ::protobuf::RepeatedField<::std::vec::Vec<u8>>) {
        self.cids_bytes = v;
    }

    // Mutable pointer to the field.
    pub fn mut_cids_bytes(&mut self) -> &mut ::protobuf::RepeatedField<::std::vec::Vec<u8>> {
        &mut self.cids_bytes
    }

    // Take field
    pub fn take_cids_bytes(&mut self) -> ::protobuf::RepeatedField<::std::vec::Vec<u8>> {
        ::std::mem::replace(&mut self.cids_bytes, ::protobuf::RepeatedField::new())
    }

    // repeated .pb.ServerSource servers = 3;


    pub fn get_servers(&self) -> &[ServerSource] {
        &self.servers
    }
    pub fn clear_servers(&mut self) {
        self.servers.clear();
    }

    // Param is passed by value, moved
    pub fn set_servers(&mut self, v: ::protobuf::RepeatedField<ServerSource>) {
        self.servers = v;
    }

    // Mutable pointer to the field.
    pub fn mut_servers(&mut self) -> &mut ::protobuf::RepeatedField<ServerSource> {
        &mut self.servers
    }

    // Take field
    pub fn take_servers(&mut self) -> ::protobuf::RepeatedField<ServerSource> {
        ::std::mem::replace(&mut self.servers, ::protobuf::RepeatedField::new())
    }

    // int32 replication_factor = 4;


    pub fn get_replication_factor(&self) -> i32 {
        self.replication_factor
    }
    pub fn clear_replication_factor(&mut self) {
        self.replication_factor = 0;
    }

    // Param is passed by value, moved
    pub fn set_replication_factor(&mut self, v: i32) {
        self.replication_factor = v;
    }

    // int32 refresh_interval_seconds = 5;


    pub fn get_refresh_interval_seconds(&self) -> i32 {
        self.refresh_interval_seconds
    }
    pub fn clear_refresh_interval_seconds(&mut self) {
        self.refresh_interval_seconds = 0;
    }

    // Param is passed by value, moved
    pub fn set_refresh_interval_seconds(&mut self, v: i32) {
        self.refresh_interval_seconds = v;
    }

    // int32 server_down_delay_seconds = 6;


    pub fn get_server_down_delay_seconds(&self) -> i32 {
        self.server_down_delay_seconds
    }
    pub fn clear_server_down_delay_seconds(&mut self) {
        self.server_down_delay_seconds = 0;
    }

    // Param is passed by value, moved
    pub fn set_server_down_delay_seconds(&mut self, v: i32) {
        self.server_down_delay_seconds = v;
    }
}

impl ::protobuf::Message for Replication {
    fn is_initialized(&self) -> bool {
        for v in &self.servers {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.header)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_bytes_into(wire_type, is, &mut self.cids_bytes)?;
                },
                3 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.servers)?;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.replication_factor = tmp;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.refresh_interval_seconds = tmp;
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.server_down_delay_seconds = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.header.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.header);
        }
        for value in &self.cids_bytes {
            my_size += ::protobuf::rt::bytes_size(2, &value);
        };
        for value in &self.servers {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if self.replication_factor != 0 {
            my_size += ::protobuf::rt::value_size(4, self.replication_factor, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.refresh_interval_seconds != 0 {
            my_size += ::protobuf::rt::value_size(5, self.refresh_interval_seconds, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.server_down_delay_seconds != 0 {
            my_size += ::protobuf::rt::value_size(6, self.server_down_delay_seconds, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.header.is_empty() {
            os.write_string(1, &self.header)?;
        }
        for v in &self.cids_bytes {
            os.write_bytes(2, &v)?;
        };
        for v in &self.servers {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if self.replication_factor != 0 {
            os.write_int32(4, self.replication_factor)?;
        }
        if self.refresh_interval_seconds != 0 {
            os.write_int32(5, self.refresh_interval_seconds)?;
        }
        if self.server_down_delay_seconds != 0 {
            os.write_int32(6, self.server_down_delay_seconds)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Replication {
        Replication::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "header",
                    |m: &Replication| { &m.header },
                    |m: &mut Replication| { &mut m.header },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "cids_bytes",
                    |m: &Replication| { &m.cids_bytes },
                    |m: &mut Replication| { &mut m.cids_bytes },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ServerSource>>(
                    "servers",
                    |m: &Replication| { &m.servers },
                    |m: &mut Replication| { &mut m.servers },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "replication_factor",
                    |m: &Replication| { &m.replication_factor },
                    |m: &mut Replication| { &mut m.replication_factor },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "refresh_interval_seconds",
                    |m: &Replication| { &m.refresh_interval_seconds },
                    |m: &mut Replication| { &mut m.refresh_interval_seconds },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "server_down_delay_seconds",
                    |m: &Replication| { &m.server_down_delay_seconds },
                    |m: &mut Replication| { &mut m.server_down_delay_seconds },
                ));
                ::protobuf::reflect::MessageDescriptor::new_pb_name::<Replication>(
                    "Replication",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Replication {
        static mut instance: ::protobuf::lazy::Lazy<Replication> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            instance.get(Replication::new)
        }
    }
}

impl ::protobuf::Clear for Replication {
    fn clear(&mut self) {
        self.header.clear();
        self.cids_bytes.clear();
        self.servers.clear();
        self.replication_factor = 0;
        self.refresh_interval_seconds = 0;
        self.server_down_delay_seconds = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Replication {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Replication {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ServerSource {
    // message fields
    pub addr_info: ::protobuf::SingularPtrField<AddrInfo>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ServerSource {
    fn default() -> &'a ServerSource {
        <ServerSource as ::protobuf::Message>::default_instance()
    }
}

impl ServerSource {
    pub fn new() -> ServerSource {
        ::std::default::Default::default()
    }

    // .pb.AddrInfo addr_info = 1;


    pub fn get_addr_info(&self) -> &AddrInfo {
        self.addr_info.as_ref().unwrap_or_else(|| AddrInfo::default_instance())
    }
    pub fn clear_addr_info(&mut self) {
        self.addr_info.clear();
    }

    pub fn has_addr_info(&self) -> bool {
        self.addr_info.is_some()
    }

    // Param is passed by value, moved
    pub fn set_addr_info(&mut self, v: AddrInfo) {
        self.addr_info = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_addr_info(&mut self) -> &mut AddrInfo {
        if self.addr_info.is_none() {
            self.addr_info.set_default();
        }
        self.addr_info.as_mut().unwrap()
    }

    // Take field
    pub fn take_addr_info(&mut self) -> AddrInfo {
        self.addr_info.take().unwrap_or_else(|| AddrInfo::new())
    }
}

impl ::protobuf::Message for ServerSource {
    fn is_initialized(&self) -> bool {
        for v in &self.addr_info {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.addr_info)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.addr_info.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.addr_info.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ServerSource {
        ServerSource::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<AddrInfo>>(
                    "addr_info",
                    |m: &ServerSource| { &m.addr_info },
                    |m: &mut ServerSource| { &mut m.addr_info },
                ));
                ::protobuf::reflect::MessageDescriptor::new_pb_name::<ServerSource>(
                    "ServerSource",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ServerSource {
        static mut instance: ::protobuf::lazy::Lazy<ServerSource> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            instance.get(ServerSource::new)
        }
    }
}

impl ::protobuf::Clear for ServerSource {
    fn clear(&mut self) {
        self.addr_info.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ServerSource {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ServerSource {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct AddrInfo {
    // message fields
    pub id_bytes: ::std::vec::Vec<u8>,
    pub addrs_bytes: ::protobuf::RepeatedField<::std::vec::Vec<u8>>,
    pub grpc_port: i32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a AddrInfo {
    fn default() -> &'a AddrInfo {
        <AddrInfo as ::protobuf::Message>::default_instance()
    }
}

impl AddrInfo {
    pub fn new() -> AddrInfo {
        ::std::default::Default::default()
    }

    // bytes id_bytes = 1;


    pub fn get_id_bytes(&self) -> &[u8] {
        &self.id_bytes
    }
    pub fn clear_id_bytes(&mut self) {
        self.id_bytes.clear();
    }

    // Param is passed by value, moved
    pub fn set_id_bytes(&mut self, v: ::std::vec::Vec<u8>) {
        self.id_bytes = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_id_bytes(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.id_bytes
    }

    // Take field
    pub fn take_id_bytes(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.id_bytes, ::std::vec::Vec::new())
    }

    // repeated bytes addrs_bytes = 2;


    pub fn get_addrs_bytes(&self) -> &[::std::vec::Vec<u8>] {
        &self.addrs_bytes
    }
    pub fn clear_addrs_bytes(&mut self) {
        self.addrs_bytes.clear();
    }

    // Param is passed by value, moved
    pub fn set_addrs_bytes(&mut self, v: ::protobuf::RepeatedField<::std::vec::Vec<u8>>) {
        self.addrs_bytes = v;
    }

    // Mutable pointer to the field.
    pub fn mut_addrs_bytes(&mut self) -> &mut ::protobuf::RepeatedField<::std::vec::Vec<u8>> {
        &mut self.addrs_bytes
    }

    // Take field
    pub fn take_addrs_bytes(&mut self) -> ::protobuf::RepeatedField<::std::vec::Vec<u8>> {
        ::std::mem::replace(&mut self.addrs_bytes, ::protobuf::RepeatedField::new())
    }

    // int32 grpc_port = 3;


    pub fn get_grpc_port(&self) -> i32 {
        self.grpc_port
    }
    pub fn clear_grpc_port(&mut self) {
        self.grpc_port = 0;
    }

    // Param is passed by value, moved
    pub fn set_grpc_port(&mut self, v: i32) {
        self.grpc_port = v;
    }
}

impl ::protobuf::Message for AddrInfo {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.id_bytes)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_bytes_into(wire_type, is, &mut self.addrs_bytes)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.grpc_port = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.id_bytes.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.id_bytes);
        }
        for value in &self.addrs_bytes {
            my_size += ::protobuf::rt::bytes_size(2, &value);
        };
        if self.grpc_port != 0 {
            my_size += ::protobuf::rt::value_size(3, self.grpc_port, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.id_bytes.is_empty() {
            os.write_bytes(1, &self.id_bytes)?;
        }
        for v in &self.addrs_bytes {
            os.write_bytes(2, &v)?;
        };
        if self.grpc_port != 0 {
            os.write_int32(3, self.grpc_port)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> AddrInfo {
        AddrInfo::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "id_bytes",
                    |m: &AddrInfo| { &m.id_bytes },
                    |m: &mut AddrInfo| { &mut m.id_bytes },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "addrs_bytes",
                    |m: &AddrInfo| { &m.addrs_bytes },
                    |m: &mut AddrInfo| { &mut m.addrs_bytes },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "grpc_port",
                    |m: &AddrInfo| { &m.grpc_port },
                    |m: &mut AddrInfo| { &mut m.grpc_port },
                ));
                ::protobuf::reflect::MessageDescriptor::new_pb_name::<AddrInfo>(
                    "AddrInfo",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static AddrInfo {
        static mut instance: ::protobuf::lazy::Lazy<AddrInfo> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            instance.get(AddrInfo::new)
        }
    }
}

impl ::protobuf::Clear for AddrInfo {
    fn clear(&mut self) {
        self.id_bytes.clear();
        self.addrs_bytes.clear();
        self.grpc_port = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for AddrInfo {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AddrInfo {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Subscription {
    // message fields
    pub topic: ::std::string::String,
    pub author_id_bytes: ::std::vec::Vec<u8>,
    pub remove: bool,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Subscription {
    fn default() -> &'a Subscription {
        <Subscription as ::protobuf::Message>::default_instance()
    }
}

impl Subscription {
    pub fn new() -> Subscription {
        ::std::default::Default::default()
    }

    // string topic = 1;


    pub fn get_topic(&self) -> &str {
        &self.topic
    }
    pub fn clear_topic(&mut self) {
        self.topic.clear();
    }

    // Param is passed by value, moved
    pub fn set_topic(&mut self, v: ::std::string::String) {
        self.topic = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_topic(&mut self) -> &mut ::std::string::String {
        &mut self.topic
    }

    // Take field
    pub fn take_topic(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.topic, ::std::string::String::new())
    }

    // bytes author_id_bytes = 2;


    pub fn get_author_id_bytes(&self) -> &[u8] {
        &self.author_id_bytes
    }
    pub fn clear_author_id_bytes(&mut self) {
        self.author_id_bytes.clear();
    }

    // Param is passed by value, moved
    pub fn set_author_id_bytes(&mut self, v: ::std::vec::Vec<u8>) {
        self.author_id_bytes = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_author_id_bytes(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.author_id_bytes
    }

    // Take field
    pub fn take_author_id_bytes(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.author_id_bytes, ::std::vec::Vec::new())
    }

    // bool remove = 3;


    pub fn get_remove(&self) -> bool {
        self.remove
    }
    pub fn clear_remove(&mut self) {
        self.remove = false;
    }

    // Param is passed by value, moved
    pub fn set_remove(&mut self, v: bool) {
        self.remove = v;
    }
}

impl ::protobuf::Message for Subscription {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.topic)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.author_id_bytes)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.remove = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.topic.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.topic);
        }
        if !self.author_id_bytes.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.author_id_bytes);
        }
        if self.remove != false {
            my_size += 2;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.topic.is_empty() {
            os.write_string(1, &self.topic)?;
        }
        if !self.author_id_bytes.is_empty() {
            os.write_bytes(2, &self.author_id_bytes)?;
        }
        if self.remove != false {
            os.write_bool(3, self.remove)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Subscription {
        Subscription::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "topic",
                    |m: &Subscription| { &m.topic },
                    |m: &mut Subscription| { &mut m.topic },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "author_id_bytes",
                    |m: &Subscription| { &m.author_id_bytes },
                    |m: &mut Subscription| { &mut m.author_id_bytes },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "remove",
                    |m: &Subscription| { &m.remove },
                    |m: &mut Subscription| { &mut m.remove },
                ));
                ::protobuf::reflect::MessageDescriptor::new_pb_name::<Subscription>(
                    "Subscription",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Subscription {
        static mut instance: ::protobuf::lazy::Lazy<Subscription> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            instance.get(Subscription::new)
        }
    }
}

impl ::protobuf::Clear for Subscription {
    fn clear(&mut self) {
        self.topic.clear();
        self.author_id_bytes.clear();
        self.remove = false;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Subscription {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Subscription {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ReplicationStatus {
    // message fields
    pub ok: bool,
    pub is_active: bool,
    pub current_version: i64,
    pub target_version: i64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ReplicationStatus {
    fn default() -> &'a ReplicationStatus {
        <ReplicationStatus as ::protobuf::Message>::default_instance()
    }
}

impl ReplicationStatus {
    pub fn new() -> ReplicationStatus {
        ::std::default::Default::default()
    }

    // bool ok = 1;


    pub fn get_ok(&self) -> bool {
        self.ok
    }
    pub fn clear_ok(&mut self) {
        self.ok = false;
    }

    // Param is passed by value, moved
    pub fn set_ok(&mut self, v: bool) {
        self.ok = v;
    }

    // bool is_active = 2;


    pub fn get_is_active(&self) -> bool {
        self.is_active
    }
    pub fn clear_is_active(&mut self) {
        self.is_active = false;
    }

    // Param is passed by value, moved
    pub fn set_is_active(&mut self, v: bool) {
        self.is_active = v;
    }

    // int64 current_version = 3;


    pub fn get_current_version(&self) -> i64 {
        self.current_version
    }
    pub fn clear_current_version(&mut self) {
        self.current_version = 0;
    }

    // Param is passed by value, moved
    pub fn set_current_version(&mut self, v: i64) {
        self.current_version = v;
    }

    // int64 target_version = 4;


    pub fn get_target_version(&self) -> i64 {
        self.target_version
    }
    pub fn clear_target_version(&mut self) {
        self.target_version = 0;
    }

    // Param is passed by value, moved
    pub fn set_target_version(&mut self, v: i64) {
        self.target_version = v;
    }
}

impl ::protobuf::Message for ReplicationStatus {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.ok = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.is_active = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.current_version = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.target_version = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.ok != false {
            my_size += 2;
        }
        if self.is_active != false {
            my_size += 2;
        }
        if self.current_version != 0 {
            my_size += ::protobuf::rt::value_size(3, self.current_version, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.target_version != 0 {
            my_size += ::protobuf::rt::value_size(4, self.target_version, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.ok != false {
            os.write_bool(1, self.ok)?;
        }
        if self.is_active != false {
            os.write_bool(2, self.is_active)?;
        }
        if self.current_version != 0 {
            os.write_int64(3, self.current_version)?;
        }
        if self.target_version != 0 {
            os.write_int64(4, self.target_version)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ReplicationStatus {
        ReplicationStatus::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "ok",
                    |m: &ReplicationStatus| { &m.ok },
                    |m: &mut ReplicationStatus| { &mut m.ok },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "is_active",
                    |m: &ReplicationStatus| { &m.is_active },
                    |m: &mut ReplicationStatus| { &mut m.is_active },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "current_version",
                    |m: &ReplicationStatus| { &m.current_version },
                    |m: &mut ReplicationStatus| { &mut m.current_version },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "target_version",
                    |m: &ReplicationStatus| { &m.target_version },
                    |m: &mut ReplicationStatus| { &mut m.target_version },
                ));
                ::protobuf::reflect::MessageDescriptor::new_pb_name::<ReplicationStatus>(
                    "ReplicationStatus",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ReplicationStatus {
        static mut instance: ::protobuf::lazy::Lazy<ReplicationStatus> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            instance.get(ReplicationStatus::new)
        }
    }
}

impl ::protobuf::Clear for ReplicationStatus {
    fn clear(&mut self) {
        self.ok = false;
        self.is_active = false;
        self.current_version = 0;
        self.target_version = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ReplicationStatus {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ReplicationStatus {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct SubscriptionUpdate {
    // message fields
    pub version: i64,
    pub replication_bytes: ::std::vec::Vec<u8>,
    pub signature: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SubscriptionUpdate {
    fn default() -> &'a SubscriptionUpdate {
        <SubscriptionUpdate as ::protobuf::Message>::default_instance()
    }
}

impl SubscriptionUpdate {
    pub fn new() -> SubscriptionUpdate {
        ::std::default::Default::default()
    }

    // int64 version = 1;


    pub fn get_version(&self) -> i64 {
        self.version
    }
    pub fn clear_version(&mut self) {
        self.version = 0;
    }

    // Param is passed by value, moved
    pub fn set_version(&mut self, v: i64) {
        self.version = v;
    }

    // bytes replication_bytes = 2;


    pub fn get_replication_bytes(&self) -> &[u8] {
        &self.replication_bytes
    }
    pub fn clear_replication_bytes(&mut self) {
        self.replication_bytes.clear();
    }

    // Param is passed by value, moved
    pub fn set_replication_bytes(&mut self, v: ::std::vec::Vec<u8>) {
        self.replication_bytes = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_replication_bytes(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.replication_bytes
    }

    // Take field
    pub fn take_replication_bytes(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.replication_bytes, ::std::vec::Vec::new())
    }

    // bytes signature = 3;


    pub fn get_signature(&self) -> &[u8] {
        &self.signature
    }
    pub fn clear_signature(&mut self) {
        self.signature.clear();
    }

    // Param is passed by value, moved
    pub fn set_signature(&mut self, v: ::std::vec::Vec<u8>) {
        self.signature = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_signature(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.signature
    }

    // Take field
    pub fn take_signature(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.signature, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for SubscriptionUpdate {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.version = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.replication_bytes)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.signature)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.version != 0 {
            my_size += ::protobuf::rt::value_size(1, self.version, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.replication_bytes.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.replication_bytes);
        }
        if !self.signature.is_empty() {
            my_size += ::protobuf::rt::bytes_size(3, &self.signature);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.version != 0 {
            os.write_int64(1, self.version)?;
        }
        if !self.replication_bytes.is_empty() {
            os.write_bytes(2, &self.replication_bytes)?;
        }
        if !self.signature.is_empty() {
            os.write_bytes(3, &self.signature)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SubscriptionUpdate {
        SubscriptionUpdate::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "version",
                    |m: &SubscriptionUpdate| { &m.version },
                    |m: &mut SubscriptionUpdate| { &mut m.version },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "replication_bytes",
                    |m: &SubscriptionUpdate| { &m.replication_bytes },
                    |m: &mut SubscriptionUpdate| { &mut m.replication_bytes },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "signature",
                    |m: &SubscriptionUpdate| { &m.signature },
                    |m: &mut SubscriptionUpdate| { &mut m.signature },
                ));
                ::protobuf::reflect::MessageDescriptor::new_pb_name::<SubscriptionUpdate>(
                    "SubscriptionUpdate",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static SubscriptionUpdate {
        static mut instance: ::protobuf::lazy::Lazy<SubscriptionUpdate> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            instance.get(SubscriptionUpdate::new)
        }
    }
}

impl ::protobuf::Clear for SubscriptionUpdate {
    fn clear(&mut self) {
        self.version = 0;
        self.replication_bytes.clear();
        self.signature.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SubscriptionUpdate {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SubscriptionUpdate {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct SignedSubscription {
    // message fields
    pub sub_part: ::protobuf::SingularPtrField<Subscription>,
    pub update_part: ::protobuf::SingularPtrField<SubscriptionUpdate>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SignedSubscription {
    fn default() -> &'a SignedSubscription {
        <SignedSubscription as ::protobuf::Message>::default_instance()
    }
}

impl SignedSubscription {
    pub fn new() -> SignedSubscription {
        ::std::default::Default::default()
    }

    // .pb.Subscription sub_part = 1;


    pub fn get_sub_part(&self) -> &Subscription {
        self.sub_part.as_ref().unwrap_or_else(|| Subscription::default_instance())
    }
    pub fn clear_sub_part(&mut self) {
        self.sub_part.clear();
    }

    pub fn has_sub_part(&self) -> bool {
        self.sub_part.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sub_part(&mut self, v: Subscription) {
        self.sub_part = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_sub_part(&mut self) -> &mut Subscription {
        if self.sub_part.is_none() {
            self.sub_part.set_default();
        }
        self.sub_part.as_mut().unwrap()
    }

    // Take field
    pub fn take_sub_part(&mut self) -> Subscription {
        self.sub_part.take().unwrap_or_else(|| Subscription::new())
    }

    // .pb.SubscriptionUpdate update_part = 2;


    pub fn get_update_part(&self) -> &SubscriptionUpdate {
        self.update_part.as_ref().unwrap_or_else(|| SubscriptionUpdate::default_instance())
    }
    pub fn clear_update_part(&mut self) {
        self.update_part.clear();
    }

    pub fn has_update_part(&self) -> bool {
        self.update_part.is_some()
    }

    // Param is passed by value, moved
    pub fn set_update_part(&mut self, v: SubscriptionUpdate) {
        self.update_part = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_update_part(&mut self) -> &mut SubscriptionUpdate {
        if self.update_part.is_none() {
            self.update_part.set_default();
        }
        self.update_part.as_mut().unwrap()
    }

    // Take field
    pub fn take_update_part(&mut self) -> SubscriptionUpdate {
        self.update_part.take().unwrap_or_else(|| SubscriptionUpdate::new())
    }
}

impl ::protobuf::Message for SignedSubscription {
    fn is_initialized(&self) -> bool {
        for v in &self.sub_part {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.update_part {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.sub_part)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.update_part)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.sub_part.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.update_part.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.sub_part.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.update_part.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SignedSubscription {
        SignedSubscription::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Subscription>>(
                    "sub_part",
                    |m: &SignedSubscription| { &m.sub_part },
                    |m: &mut SignedSubscription| { &mut m.sub_part },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<SubscriptionUpdate>>(
                    "update_part",
                    |m: &SignedSubscription| { &m.update_part },
                    |m: &mut SignedSubscription| { &mut m.update_part },
                ));
                ::protobuf::reflect::MessageDescriptor::new_pb_name::<SignedSubscription>(
                    "SignedSubscription",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static SignedSubscription {
        static mut instance: ::protobuf::lazy::Lazy<SignedSubscription> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            instance.get(SignedSubscription::new)
        }
    }
}

impl ::protobuf::Clear for SignedSubscription {
    fn clear(&mut self) {
        self.sub_part.clear();
        self.update_part.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SignedSubscription {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SignedSubscription {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11replication.proto\x12\x02pb\"\x94\x02\n\x0bReplication\x12\x16\n\
    \x06header\x18\x01\x20\x01(\tR\x06header\x12\x1d\n\ncids_bytes\x18\x02\
    \x20\x03(\x0cR\tcidsBytes\x12*\n\x07servers\x18\x03\x20\x03(\x0b2\x10.pb\
    .ServerSourceR\x07servers\x12-\n\x12replication_factor\x18\x04\x20\x01(\
    \x05R\x11replicationFactor\x128\n\x18refresh_interval_seconds\x18\x05\
    \x20\x01(\x05R\x16refreshIntervalSeconds\x129\n\x19server_down_delay_sec\
    onds\x18\x06\x20\x01(\x05R\x16serverDownDelaySeconds\"9\n\x0cServerSourc\
    e\x12)\n\taddr_info\x18\x01\x20\x01(\x0b2\x0c.pb.AddrInfoR\x08addrInfo\"\
    c\n\x08AddrInfo\x12\x19\n\x08id_bytes\x18\x01\x20\x01(\x0cR\x07idBytes\
    \x12\x1f\n\x0baddrs_bytes\x18\x02\x20\x03(\x0cR\naddrsBytes\x12\x1b\n\tg\
    rpc_port\x18\x03\x20\x01(\x05R\x08grpcPort\"d\n\x0cSubscription\x12\x14\
    \n\x05topic\x18\x01\x20\x01(\tR\x05topic\x12&\n\x0fauthor_id_bytes\x18\
    \x02\x20\x01(\x0cR\rauthorIdBytes\x12\x16\n\x06remove\x18\x03\x20\x01(\
    \x08R\x06remove\"\x90\x01\n\x11ReplicationStatus\x12\x0e\n\x02ok\x18\x01\
    \x20\x01(\x08R\x02ok\x12\x1b\n\tis_active\x18\x02\x20\x01(\x08R\x08isAct\
    ive\x12'\n\x0fcurrent_version\x18\x03\x20\x01(\x03R\x0ecurrentVersion\
    \x12%\n\x0etarget_version\x18\x04\x20\x01(\x03R\rtargetVersion\"y\n\x12S\
    ubscriptionUpdate\x12\x18\n\x07version\x18\x01\x20\x01(\x03R\x07version\
    \x12+\n\x11replication_bytes\x18\x02\x20\x01(\x0cR\x10replicationBytes\
    \x12\x1c\n\tsignature\x18\x03\x20\x01(\x0cR\tsignature\"z\n\x12SignedSub\
    scription\x12+\n\x08sub_part\x18\x01\x20\x01(\x0b2\x10.pb.SubscriptionR\
    \x07subPart\x127\n\x0bupdate_part\x18\x02\x20\x01(\x0b2\x16.pb.Subscript\
    ionUpdateR\nupdatePart2\xfc\x01\n\nreplicator\x120\n\x03Add\x12\x10.pb.S\
    ubscription\x1a\x15.pb.ReplicationStatus0\x01\x123\n\x06Status\x12\x10.p\
    b.Subscription\x1a\x15.pb.ReplicationStatus0\x01\x12A\n\x15GetSubscripti\
    onUpdate\x12\x10.pb.Subscription\x1a\x16.pb.SubscriptionUpdate\x12D\n\
    \x11SubmitReplication\x12\x16.pb.SignedSubscription\x1a\x15.pb.Replicati\
    onStatus0\x01b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
